import { ColorType } from './colors-types';
export declare type BorderRadiusType = 'none' | 'sm' | true | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | 'full';
export declare type BorderWidthType = '0' | '2' | '4' | '8' | true;
export declare type BorderColorType = ColorType;
export declare type BorderStyleType = 'solid' | 'dashed' | 'dotted' | 'double' | 'hidden' | 'none';
export declare type DivideWidthType = '0' | '2' | '4' | '8' | true | 'reverse';
export declare type DivideColorType = ColorType;
export declare type DivideStyleType = 'solid' | 'dashed' | 'dotted' | 'double' | 'hidden' | 'none';
export declare type OutlineWidthType = '0' | '1' | '2' | '4' | '8';
export declare type OutlineColorType = ColorType;
export declare type OutlineStyleType = 'none' | true | 'dashed' | 'dotted' | 'double' | 'hidden';
export declare type OutlineOffsetType = '0' | '1' | '2' | '4' | '8';
export declare type RingWidthType = '0' | '1' | '2' | true | '4' | '8' | 'inset';
export declare type RingColorType = ColorType;
export declare type RingOffsetType = '0' | '1' | '2' | '4' | '8';
export declare type RingOffsetColorType = ColorType;
export interface BordersProps {
    rounded?: BorderRadiusType;
    borderWidth?: BorderWidthType;
    borderXWidth?: BorderWidthType;
    borderYWidth?: BorderWidthType;
    borderTWidth?: BorderWidthType;
    borderRWidth?: BorderWidthType;
    borderBWidth?: BorderWidthType;
    borderLWidth?: BorderWidthType;
    borderColor?: BorderColorType;
    borderStyle?: BorderStyleType;
    divideXWidth?: DivideWidthType;
    divideYWidth?: DivideWidthType;
    divideColor?: DivideColorType;
    divideStyle?: DivideStyleType;
    outlineWidth?: OutlineWidthType;
    outlineColor?: OutlineColorType;
    outlineStyle?: OutlineStyleType;
    outlineOffset?: OutlineOffsetType;
    ringWidth?: RingWidthType;
    ringColor?: RingColorType;
    ringOffset?: RingOffsetType;
    ringOffsetColor?: RingOffsetColorType;
}
export declare const BordersClassNames: (props: BordersProps) => string;
//# sourceMappingURL=borders-types.d.ts.map