export declare type BlurType = 'none' | 'sm' | true | 'md' | 'lg' | 'xl' | '2xl' | '3xl';
export declare type BrightnessType = '0' | '50' | '75' | '90' | '95' | '100' | '105' | '110' | '125' | '150' | '200';
export declare type ContrastType = '0' | '50' | '75' | '100' | '125' | '150' | '200';
export declare type DropShadowType = 'none' | 'sm' | true | 'md' | 'lg' | 'xl' | '2xl';
export declare type GrayscaleType = boolean;
export declare type HueRotateType = '0' | '15' | '30' | '60' | '90' | '180';
export declare type InvertType = boolean;
export declare type SaturateType = '0' | '50' | '100' | '150' | '200';
export declare type SepiaType = boolean;
export declare type BackdropBlurType = 'none' | 'sm' | true | 'md' | 'lg' | 'xl' | '2xl' | '3xl';
export declare type BackdropBrightnessType = '0' | '50' | '75' | '90' | '95' | '100' | '105' | '110' | '125' | '150' | '200';
export declare type BackdropContrastType = '0' | '50' | '75' | '100' | '125' | '150' | '200';
export declare type BackdropGrayscaleType = boolean;
export declare type BackdropHueRotateType = '0' | '15' | '30' | '60' | '90' | '180';
export declare type BackdropInvertType = boolean;
export declare type BackdropOpacityType = '0' | '5' | '10' | '20' | '25' | '30' | '40' | '50' | '60' | '70' | '75' | '80' | '90' | '95' | '100';
export declare type BackdropSaturateType = '0' | '50' | '100' | '150' | '200';
export declare type BackdropSepiaType = boolean;
export interface FiltersProps {
    blur?: BlurType;
    brightness?: BrightnessType;
    contrast?: ContrastType;
    dropShadow?: DropShadowType;
    grayscale?: GrayscaleType;
    hueRotate?: HueRotateType;
    invert?: InvertType;
    saturate?: SaturateType;
    sepia?: SepiaType;
    backdropBlur?: BackdropBlurType;
    backdropBrightness?: BackdropBrightnessType;
    backdropContrast?: BackdropContrastType;
    backdropGrayscale?: BackdropGrayscaleType;
    backdropHueRotate?: BackdropHueRotateType;
    backdropInvert?: BackdropInvertType;
    backdropOpacity?: BackdropOpacityType;
    backdropSaturate?: BackdropSaturateType;
    backdropSepia?: BackdropSepiaType;
}
export declare const FiltersClassNames: (props: FiltersProps) => string;
//# sourceMappingURL=filter-types.d.ts.map